### ISSUE TITLE
Ginga: Switch from aggdraw to pycairo

### ISSUE THREAD

**Issue by pllim** [astropy/astrowidgets#130]
@ejeschke said pycairo will provide the most capability. Perhaps he can elaborate.

**Comment by ejeschke** [comment]
Thinking about this a little more, I think I withdraw the comment--`aggdraw` should be as capable as `pycairo`, and probably faster as well. However, `pycairo`, 'pillow` and `opencv` are all installable even in default conda environments, whereas `aggdraw` you have to install from git, presently.  `pycairo` does support all (I think) attributes of ginga canvas objects line properties, such as dashed lines, various line thicknesses, full alpha fills with transparency, etc.

`aggdraw` does also, IIRC, but since `pycairo` is in the conda environment and used by so many other projects, it's probably the better choice. As Ginga will check to see what is installed and pick the preferred renderer (cairo), I don't think you need to do anything special on the astrowidgets side unless you are specifically requesting a particular renderer.

**Comment by pllim** [comment]
@ejeschke , should we update https://astrowidgets.readthedocs.io/en/latest/install.html to omit aggdraw and replace the dependency list with cairo then?
