### ISSUE TITLE
TST: devdeps broken because _mouse_click_cb creates canvas object with coord being None

### ISSUE THREAD

**Issue by pllim** [astropy/astrowidgets#154]
@ejeschke , do you know what happened here? This is happening with dev version of Ginga (but not the released version) and I cannot keep track of the massive refactoring that you recently did, so any advice would be greatly appreciated. Thanks!

Example log: https://github.com/astropy/astrowidgets/actions/runs/3391388780/jobs/5636513716

Minimal reproducible code:

```python
import numpy as np
from astropy.table import Table
from astrowidgets.core import ImageWidget

# The widget
npix_side = 200
image = ImageWidget(image_width=npix_side, image_height=npix_side)

# The markers
x = np.array([20, 30, 40])
y = np.array([40, 80, 100])
input_markers = Table(data=[x, y], names=['x', 'y'])

# "Interactive" marking
image._is_marking = True
for data_x, data_y in input_markers:
    image._mouse_click_cb(image._viewer, None, data_x, data_y)

c_mark = image._viewer.canvas.get_object_by_tag('interactive-markers')
circ = c_mark.objects[0]
assert circ.coord == 'data'  # This will fail because circ.coord is None
```

https://github.com/astropy/astrowidgets/blob/7a8ba86b2719d185335da0de8732c86232530867/astrowidgets/core.py#L224

**Comment by ejeschke** [comment]
I think that is due to a very recent change in `CanvasObject` where a canvas object's `coord` attribute used to default to 'data' but now defaults to None. But None will assign a data mapper when the object is added to a canvas--so the result is still the same. The reason for change was to allow the user to set a coordinate mapper for the canvas and have objects inherit that if they don't assign their own.

You can safely change that assertion to:
```python
assert circ.coord in (None, 'data')
```

**Comment by ejeschke** [comment]
Sorry for the confusion!

**Comment by ejeschke** [comment]
You can also assign `coord='data' when creating the `Circle`, if you prefer.

**Comment by pllim** [comment]
Thanks, @ejeschke !
