### ISSUE TITLE
Ginga zoom keys conflict with notebook/lab heading keys

### ISSUE THREAD

**Issue by eteq** [astropy/astrowidgets#44]
I think this is a jupyterlab thing (i.e., it might not work this way in the notebook), but when I have the widget up and hit a number key to zoom, the event apparently gets passed onto the lab and it will change whatever cell I have selected into a header-level (the default Jupyter behavior).  If it happens to be the cell containing the image widget, it hard-crashes the lab and I have to refresh the browser to get anything to work.

Sort of vaguely related to #39 since it might be the easiest way around it

**Comment by mwcraig** [comment]
@eteq -- could you try updating your ipyevents version? Turns out that there was an issue in ipyevents with lab.

**Comment by mwcraig** [comment]
Just ran into this myself. The lab didn't crash, but "-" collapsed the cell the image was in rather than zooming out. In addition, context menus keep popping up when they shouldn't be.

**Comment by mwcraig** [comment]
Note to self: this is going to be difficult to resolve. Lab intercepts keydown events very early in the browser event handling process (capture phase, with a handler on the top-level document) and stops their further propagation. This is done to implement a lab-wide keyboard shortcut manager; rather than trying to short-circuit this I need to find a way to work within the shortcut system, I think. The (ugly) alternative is to add a document-level shortcut that captures the events first.
