### ISSUE TITLE
Should markers be erased when the image changes?

### ISSUE THREAD

**Issue by mwcraig** [astropy/astrowidgets#57]
I can see arguments both ways, opening to remember to come back to this....

**Comment by pllim** [comment]
If you work on different exposures of a similar sky FOV, usually you want to keep the markers on (and aligned by RA/DEC, rather than X/Y. That is a common use case I heard of at least here at STScI. If you are just opening exposures of different fields, then it makes more sense to erase them. Perhaps this behavior can be a user configurable setting. 🤔

**Comment by pllim** [comment]
I would say "no" because in glue-jupyter backend, we want the markers to stay on even when blinking. So this question is backend specific and should be decided by each backend separately.
